<?php

namespace Proxies\__CG__\Acme\MusoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \Acme\MusoreBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setReleaseDate($releaseDate)
    {
        $this->__load();
        return parent::setReleaseDate($releaseDate);
    }

    public function getReleaseDate()
    {
        $this->__load();
        return parent::getReleaseDate();
    }

    public function setCoverLink($coverLink)
    {
        $this->__load();
        return parent::setCoverLink($coverLink);
    }

    public function getCoverLink()
    {
        $this->__load();
        return parent::getCoverLink();
    }

    public function setArtist(\Acme\MusoreBundle\Entity\Artist $artist = NULL)
    {
        $this->__load();
        return parent::setArtist($artist);
    }

    public function getArtist()
    {
        $this->__load();
        return parent::getArtist();
    }

    public function setGenre(\Acme\MusoreBundle\Entity\Genre $genre = NULL)
    {
        $this->__load();
        return parent::setGenre($genre);
    }

    public function getGenre()
    {
        $this->__load();
        return parent::getGenre();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'price', 'title', 'release_date', 'coverLink', 'artist', 'genre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}