<?php

namespace Proxies\__CG__\Acme\MusoreBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Single extends \Acme\MusoreBundle\Entity\Single implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLength($length)
    {
        $this->__load();
        return parent::setLength($length);
    }

    public function getLength()
    {
        $this->__load();
        return parent::getLength();
    }

    public function setPreviewLink($previewLink)
    {
        $this->__load();
        return parent::setPreviewLink($previewLink);
    }

    public function getPreviewLink()
    {
        $this->__load();
        return parent::getPreviewLink();
    }

    public function setProduct(\Acme\MusoreBundle\Entity\Product $product = NULL)
    {
        $this->__load();
        return parent::setProduct($product);
    }

    public function getProduct()
    {
        $this->__load();
        return parent::getProduct();
    }

    public function addAlbumTrack(\Acme\MusoreBundle\Entity\AlbumTrack $albumTracks)
    {
        $this->__load();
        return parent::addAlbumTrack($albumTracks);
    }

    public function removeAlbumTrack(\Acme\MusoreBundle\Entity\AlbumTrack $albumTracks)
    {
        $this->__load();
        return parent::removeAlbumTrack($albumTracks);
    }

    public function getAlbumTracks()
    {
        $this->__load();
        return parent::getAlbumTracks();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'length', 'previewLink', 'product', 'albumTracks');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}