security:
    encoders:
        Acme\MusoreBundle\Entity\Customer: sha512
        Symfony\Component\Security\Core\User\User: plaintext



    providers:
        main:
            entity: { class: Acme\MusoreBundle\Entity\Customer, property:username}
        in_memory:
            memory:
                users:
                    ryan:  { password: test, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: musore_homepage
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/album, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/favorites, roles: ['ROLE_USER']}
        - { path: ^/downloads, roles: ['ROLE_USER']}
        - { path: ^/cart, roles:  IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}


